### ISSUE TITLE
mobx 6.x support

### ISSUE THREAD

**Issue by ruudandriessen** [kitze/mobx-router#106]
Using the mobx-router package doesn't work under mobx 6.x since `makeObservable` is now required in order to register observables (ref: https://mobx.js.org/observable-state.html). Most notably, this causes  `goTo` to no longer work.

As a workaround it would be possible to use `makeAutoObservable(routerStore)`. 
However, that should at least be documented.

**Comment by mitche50** [comment]
Just noticed this, been banging my head against this for a while.  An update to the docs would really help here.

**Comment by thdk** [comment]
Hi, can you try with mobx-router v1.0.0?

**Comment by chuanhhoang** [comment]
It doesn't work. goTo doesn't trigger rendering.

**Comment by thdk** [comment]
> It doesn't work. goTo doesn't trigger rendering.

I have updated the sample repo (https://github.com/thdk/mobx-router-typescript-example) and everything seems to be working fine there. Although it is very possible not all cases are covered in that example project. If so can you submit a PR to the sample repo that shows a reproduction of this issue?

Otherwise, some things to try:
- did you verify the mobx versions in your project? What shows you when you run `npm ls mobx`. 
- did you follow the mobx6 upgrade steps? https://mobx.js.org/migrating-from-4-or-5.html
